name: talky_chat
description: A flutter chat app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # API
  http: ^1.1.0

  # JSON
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.0.5
  
  # Provider
  provider: ^6.1.1

  # Styling
  flutter_native_splash: ^2.3.7
  lottie: ^2.7.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  random_avatar: ^0.0.8

  # Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # OS API
  flutter_local_notifications: ^16.2.0

  # Permissions
  permission_handler: ^11.0.0

  # Security
  crypto: ^3.0.3
  uuid: ^4.2.2

  # Media
  image_picker: ^1.0.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Thin.ttf
        weight: 100
      - asset: assets/fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Inter-Light.ttf
        weight: 300
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Inter-Black.ttf
        weight: 900

flutter_native_splash:
  color: "#377DFF"
  image: "assets/images/Talky_1152.png"
  android: true
  ios: true
  android_12:
    color: "#377DFF"
    icon_background_color: "#377DFF"
    image: "assets/images/Talky_1152.png"
